In [134]:
from oqd_compiler_infrastructure import (
    CFGBlockAccumulator,
    Post,
    PrettyPrint,
    RelabelCFGBlocks,
)
from oqd_core.analysis.analog.cfg import AnalogCFGBuilder
from oqd_core.analysis.analog.dim_checker import DimensionChecker
from oqd_core.analysis.analog.reaching_def import AvailableVariableAnalysis
from oqd_core.analysis.analog.type_checker import AnalogTypeChecker
from oqd_core.compiler.analog.utils import analog
from oqd_core.frontend.analog import parse_analog

from oqd_analog_emulator.interpreter import AnalogInterpreter
from oqd_analog_emulator.qutip import QutipMethodTable

printer = Post(PrettyPrint())

source = """ 
r = qreg(2)

m = qmode(1)

pi = 3.1415926535

initialize(r)
initialize(m)

evolve(%X @ (%A + %C), [], pi/4,  [r[0],m[0]])

d = measure(m)
d
"""


circuit = parse_analog(source)
cfg = AnalogCFGBuilder()(circuit)
checker = AnalogTypeChecker(cfg)


In [135]:
interpreter = AnalogInterpreter(
    method_table="QutipMethodTable", fock_cutoff=4, dt=1e-4, ignore_jumps=False
)

res = interpreter.run(cfg=cfg)

print(res)

print(interpreter.vm.registers)

[0]
{RegisterName(name='r', index=0, dim=2): QuantumRegister(name=[RegisterName(name='r', index=0, dim=2)], time=0.785398163375, time_last_updated=0.785398163375, state=Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]), RegisterName(name='r', index=1, dim=2): QuantumRegister(name=[RegisterName(name='r', index=1, dim=2)], time=0.785398163375, time_last_updated=0.0, state=Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]), RegisterName(name='r', index=2, dim=4): QuantumRegister(name=[RegisterName(name='r', index=2, dim=4)], time=0.785398163375, time_last_updated=0.785398163375, state=Quantum object: dims=[[np.int64(4)], [1]], shape=(4, 1), type='ket', dtype=CSR
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]])}


In [136]:
# store = interpreter.get_store()
# store
# interpreter.vm.stack
# store['q0'].state

In [137]:
# from oqd_core.compiler.analog.math.rules import SubstituteMathVar
# from oqd_core.interface.analog.expr import MathVar
# from oqd_compiler_infrastructure import Post
# substitute_pass = Post(SubstituteMathVar(MathVar(class_='MathVar', name='#s'), MathVar(class_='MathVar', name='#t') - 10))

# substitute_pass(store['a'])
# registers = interpreter.vm.registers
# registers

In [138]:
# from oqd_compiler_infrastructure import CFGBlockAccumulator, RelabelCFGBlocks
# from oqd_core.analysis.analog.cfg import AnalogCFGBuilder
# from oqd_core.analysis.analog.dim_checker import DimensionChecker
# from oqd_core.analysis.analog.reaching_def import AvailableVariableAnalysis
# from oqd_core.analysis.analog.type_checker import AnalogTypeChecker
# from oqd_core.compiler.analog.utils import analog
# from rich import print as pprint

# from oqd_analog_emulator.instructions import (
#     AnalogInstructionsCodegen,
# )
# from oqd_analog_emulator.interpreter import AnalogInterpreter, AnalogVirtualMachine
# from oqd_analog_emulator.qutip import (
#     QutipMethodTable,
#     QutipMethodTableOptions,
# )


# # ruff: disable[F821,F841,E741]
# @analog
# def f():
#     a = 1 + 1j

#     conj(a)


# # ruff: enable[F821,F841,E741]

# cfg = AnalogCFGBuilder()(f)
# cfg = CFGBlockAccumulator()(cfg)
# cfg = RelabelCFGBlocks()(cfg)

# undef_checker = AvailableVariableAnalysis()
# undef_res = undef_checker.analyze(cfg)

# type_checker = AnalogTypeChecker()
# type_res = type_checker.analyze(cfg)

# dim_checker = DimensionChecker()
# dim_res = dim_checker.analyze(cfg)

# instrs = [AnalogInstructionsCodegen()(s) for s in f.statements]

# method_table = QutipMethodTable(options=QutipMethodTableOptions(singleshot_init=False))
# interpreter = AnalogInterpreter(method_table=method_table)

# return_values = interpreter.run(cfg)

# pprint(return_values)


# # pprint(interpreter.vm.stack)

# # pprint(interpreter.vm.store)

# # pprint(interpreter.vm.registers._registers)